<?php

namespace Viteloge\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    public function getCountByFlag( $traitement )
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('annonce.flag, count(annonce.id) as nbAnnonces')
            ->from('Viteloge\AdminBundle\Entity\Annonce', 'annonce' )
            ->where( 'annonce.traitement = :traitement' )
            ->andWhere( 'annonce.dateSuppression IS NULL' )
            ->groupby( 'annonce.flag' )
            ->setParameter( 'traitement', $traitement );
        return $qb->getQuery()->getResult();
    }

    public function getCountExported( $traitement )
    {
        $rsm = new ResultSetMapping();
        $rsm->addScalarResult( 'nbAnnonces', 'nbAnnonces' );

        $query = $this->_em->createNativeQuery(
            "SELECT COUNT(*) as nbAnnonces from export_annonce_src WHERE idAgence = :idAgence and transaction = :type", $rsm
                                               ) ->setParameter( 'idAgence', $traitement->agence->id )
            ->setParameter( 'type', $traitement->TypeTransactionTraitement );
        $x = $query->getScalarResult();
        return $x[0]['nbAnnonces'];
        
    }
    
}
