<?php

namespace Viteloge\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PileRepository extends EntityRepository
{
    public function getPileForTraitement( $traitement )
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select( 'pile' )
            ->from( 'Viteloge\AdminBundle\Entity\Pile', 'pile' )
            ->where( 'pile.traitement = :traitement' )
            ->addOrderBy( 'pile.type', 'ASC' )
            ->addOrderBy( 'pile.nextPageTraitement', 'DESC' )
            ->addOrderBy( 'pile.timestamp', 'ASC' )
            ->addOrderBy( 'pile.url', 'ASC' )
            ->setMaxResults( 500 )
            ->setParameter( 'traitement', $traitement );
        return $qb->getQuery()->getResult();
    }
    
}
