<?php

namespace Viteloge\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitementRepository extends EntityRepository
{
    public function getExclus()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select( 'traitement' )
            ->from( 'Viteloge\AdminBundle\Entity\Traitement', 'traitement' )
            ->leftJoin( 'traitement.agence', 'agence' )
            ->leftJoin( 'traitement.expression', 'expression' )
            ->where( 'traitement.Exclus = 1' );
        return $qb->getQuery()->getResult();
    }
}
