<?php

namespace Viteloge\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * XmlFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XmlFeedRepository extends EntityRepository
{
}
