parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: viteloge
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 6f7881065a19625a410e6b293b2571d55a
    database_path: null
