# jms_security_extra:
#     secure_all_services: false
#     expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:

      fos_userbundle:
        id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:

    access_control:
        - { path: ^/bundles, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        SONATA:
          - ROLE_VITELOGE_ADMIN_AGENCE_LIST
          - ROLE_VITELOGE_ADMIN_AGENCE_EDIT
          - ROLE_VITELOGE_ADMIN_AGENCE_CREATE
          - ROLE_VITELOGE_ADMIN_AGENCE_VIEW
          - ROLE_VITELOGE_ADMIN_AGENCE_DELETE
          - ROLE_VITELOGE_ADMIN_CAMPAIGN_LIST
          - ROLE_VITELOGE_ADMIN_CAMPAIGN_EDIT
          - ROLE_VITELOGE_ADMIN_CAMPAIGN_CREATE
          - ROLE_VITELOGE_ADMIN_CAMPAIGN_VIEW
          - ROLE_VITELOGE_ADMIN_CAMPAIGN_DELETE
          - ROLE_VITELOGE_ADMIN_XML_FEED_LIST
          - ROLE_VITELOGE_ADMIN_XML_FEED_EDIT
          - ROLE_VITELOGE_ADMIN_XML_FEED_CREATE
          - ROLE_VITELOGE_ADMIN_XML_FEED_DELETE
          - ROLE_VITELOGE_ADMIN_TRAITEMENT_LIST
          - ROLE_VITELOGE_ADMIN_TRAITEMENT_EDIT
          - ROLE_VITELOGE_ADMIN_TRAITEMENT_CREATE
          - ROLE_VITELOGE_ADMIN_TRAITEMENT_DELETE
          - ROLE_VITELOGE_ADMIN_PRIVILEGE_LIST
          - ROLE_VITELOGE_ADMIN_PRIVILEGE_EDIT
          - ROLE_VITELOGE_ADMIN_PRIVILEGE_CREATE
          - ROLE_VITELOGE_ADMIN_PRIVILEGE_DELETE

        # viteloge roles
        ROLE_ADVERTISEMENT: [ROLE_VITELOGE_ADMIN_CAMPAIGN_LIST,ROLE_VITELOGE_ADMIN_CAMPAIGN_EDIT,ROLE_VITELOGE_ADMIN_CAMPAIGN_CREATE,ROLE_VITELOGE_ADMIN_CAMPAIGN_VIEW,ROLE_VITELOGE_ADMIN_CAMPAIGN_DELETE]
        ROLE_AGENCY: [ROLE_USER,ROLE_VITELOGE_ADMIN_AGENCE_CREATE, ROLE_VITELOGE_ADMIN_AGENCE_LIST, ROLE_VITELOGE_ADMIN_AGENCE_EDIT,ROLE_VITELOGE_ADMIN_AGENCE_DELETE]
        ROLE_XML: [ROLE_USER,ROLE_VITELOGE_ADMIN_XML_FEED_CREATE,ROLE_VITELOGE_ADMIN_XML_FEED_EDIT,ROLE_VITELOGE_ADMIN_XML_FEED_LIST,ROLE_VITELOGE_ADMIN_XML_FEED_DELETE]
        ROLE_TRAITEMENT: [ROLE_USER,ROLE_VITELOGE_ADMIN_TRAITEMENT_CREATE,ROLE_VITELOGE_ADMIN_TRAITEMENT_EDIT,ROLE_VITELOGE_ADMIN_TRAITEMENT_LIST,ROLE_VITELOGE_ADMIN_TRAITEMENT_DELETE]
        ROLE_CONTROL: ROLE_USER
        ROLE_AGENCY_RIGHTS: [ROLE_USER,ROLE_VITELOGE_ADMIN_PRIVILEGE_CREATE,ROLE_VITELOGE_ADMIN_PRIVILEGE_EDIT,ROLE_VITELOGE_ADMIN_PRIVILEGE_LIST,ROLE_VITELOGE_ADMIN_PRIVILEGE_DELETE]
        ROLE_OPERATOR: [ROLE_AGENCY,ROLE_CONTROL,ROLE_XML,ROLE_TRAITEMENT]
        ROLE_INPUT_OPERATOR: [ROLE_VITELOGE_ADMIN_AGENCE_LIST,ROLE_VITELOGE_ADMIN_AGENCE_VIEW,ROLE_VITELOGE_ADMIN_AGENCE_EDIT,ROLE_TRAITEMENT]

        ROLE_COMMERCIAL: [ROLE_AGENCY,ROLE_AGENCY_RIGHTS,ROLE_ADVERTISEMENT]

        ROLE_ADMIN_VITELOGE: [ROLE_COMMERCIAL,ROLE_OPERATOR,ROLE_AGENCY_RIGHTS]
        # others
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_ADMIN_VITELOGE ]


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
