jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        # viteloge roles
        ROLE_ADVERTISEMENT: ROLE_USER
        ROLE_AGENCY: ROLE_USER
        ROLE_XML: ROLE_USER
        ROLE_CONTROL: ROLE_USER
        ROLE_AGENCY_RIGHTS: ROLE_USER
        ROLE_OPERATOR: [ROLE_AGENCY,ROLE_CONTROL,ROLE_XML]
        ROLE_COMMERCIAL: [ROLE_AGENCY,ROLE_AGENCY_RIGHTS,ROLE_ADVERTISEMENT]
        # others
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
